root: ./

redirects:
  out-of-band: ./guides/out-of-band.md
  desktop-welcome: ./guides/using-the-desktop-app/README.md
  desktop-help: ./guides/using-the-desktop-app/features.md
  desktop-https: ./adding-remote.it-to-your-device/find.remote.it/browser-security-warning.md
  connect-mac: ./guides/control-your-computer-remotely-mac-to-mac.md
  connect-windows: ./guides/applications/remote-graphical-desktop-access/control-your-windows-device-remotely-windows-to-windows/README.md
  connect-rpi: ./making-connections.md
  connect-linux: ./guides/using-the-desktop-app/peer-to-peer-connections.md
  minecraft: ./guides/hosting-a-minecraft-server.md
  platforms/quick-start-on-raspberry-pi/setup-your-raspberry-pi: ./platforms/quick-start-on-raspberry-pi.md
  platforms/quick-start-on-raspberry-pi/install-remote.it: ./adding-remote.it-to-your-device/the-remoteit-package-for-raspbian.md
  guides/connecting-to-a-device/proxy-connections/connecting-to-ssh: ./applications/remote-console-and-file-transfer/README.md
  guides/using-the-interactive-installer/installed-remote.it-services: ./adding-remote.it-to-your-device/using-the-interactive-installer/installed-remote.it-services.md
  guides/using-the-interactive-installer/add-a-service-to-a-lan-application: ./adding-remote.it-to-your-device/using-the-interactive-installer/add-a-service-to-an-application.md
